project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes
  
website:
  title: "Tutorials"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - sidebar:graphics
      - sidebar:extension
        
  sidebar:
    - id: extension
      title: "Extension"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - extension.qmd
        - Extension/2022-Extension-REU.qmd
        - Extension/2022-Extension-REU-slides.qmd
    - id: graphics
      title: "Graphics"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - graphics.qmd
        - text: "Creating Good Charts"
          file: Graphics/2023-REU.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



