project:
  type: website
  output-dir: docs

website:
  title: "Tutorials"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: extension.qmd
        text: Extension

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



