project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes
  
website:
  title: "Teaching Materials"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: Forensics/random-match-prob.qmd
        text: Forensics
      - sidebar:graphics
      - sidebar:extension
        
  sidebar:
    - id: extension
      title: "Extension"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - extension.qmd
        - Extension/2022-Extension-REU.qmd
        - Extension/2022-Extension-REU-slides.qmd
    - id: graphics
      title: "Graphics"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - graphics.qmd
        - text: "Creating Good Charts (2023)"
          file: Graphics/2023-REU.qmd
        # - text: "Creating Good Charts (2023 Slides)"
        #   file: Graphics/2023-REU-slides.qmd
        - text: "Creating Good Charts (2024)"
          file: Graphics/2024-REU.qmd
        # - text: "Creating Good Charts (2024 Slides)"
        #   file: Graphics/2024-REU-slides.qmd

format:
  html:   
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



