<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorials - Statistics Primer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Tutorials</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-graphics" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Graphics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-graphics">    
        <li>
    <a class="dropdown-item" href="./graphics.html" rel="" target="">
 <span class="dropdown-text">Graphics Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2023-REU.html" rel="" target="">
 <span class="dropdown-text">Creating Good Charts</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-extension" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Extension</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-extension">    
        <li>
    <a class="dropdown-item" href="./extension.html" rel="" target="">
 <span class="dropdown-text">Extension Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2022-Extension-REU.html" rel="" target="">
 <span class="dropdown-text">Statistics Primer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2022-Extension-REU-slides.html" rel="" target="">
 <span class="dropdown-text">A Short Overview of Statistics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./2022-Extension-REU.html">Statistics Primer</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extension.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extension Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2022-Extension-REU.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Statistics Primer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2022-Extension-REU-slides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A Short Overview of Statistics</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#experimental-design-and-statistical-analysis" id="toc-experimental-design-and-statistical-analysis" class="nav-link active" data-scroll-target="#experimental-design-and-statistical-analysis">Experimental Design and Statistical Analysis</a>
  <ul class="collapse">
  <li><a href="#what-is-statistics" id="toc-what-is-statistics" class="nav-link" data-scroll-target="#what-is-statistics">What is Statistics?</a></li>
  <li><a href="#an-historical-example-the-logic-of-statistical-hypothesis-testing" id="toc-an-historical-example-the-logic-of-statistical-hypothesis-testing" class="nav-link" data-scroll-target="#an-historical-example-the-logic-of-statistical-hypothesis-testing">An Historical Example: The Logic of Statistical Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#initial-statistical-setup" id="toc-initial-statistical-setup" class="nav-link" data-scroll-target="#initial-statistical-setup">Initial statistical setup</a></li>
  <li><a href="#simulation" id="toc-simulation" class="nav-link" data-scroll-target="#simulation">Simulation</a></li>
  <li><a href="#strength-of-the-evidence" id="toc-strength-of-the-evidence" class="nav-link" data-scroll-target="#strength-of-the-evidence">Strength of the Evidence</a></li>
  <li><a href="#connection-to-theory-based-tests" id="toc-connection-to-theory-based-tests" class="nav-link" data-scroll-target="#connection-to-theory-based-tests">Connection to Theory-based Tests</a></li>
  <li><a href="#understanding-p-values" id="toc-understanding-p-values" class="nav-link" data-scroll-target="#understanding-p-values">Understanding p-values</a></li>
  </ul></li>
  <li><a href="#estimating-values-confidence-intervals" id="toc-estimating-values-confidence-intervals" class="nav-link" data-scroll-target="#estimating-values-confidence-intervals">Estimating Values: Confidence Intervals</a></li>
  <li><a href="#experimental-design" id="toc-experimental-design" class="nav-link" data-scroll-target="#experimental-design">Experimental Design</a>
  <ul class="collapse">
  <li><a href="#one-sample-tests" id="toc-one-sample-tests" class="nav-link" data-scroll-target="#one-sample-tests">One Sample Tests</a></li>
  <li><a href="#two-sample-tests" id="toc-two-sample-tests" class="nav-link" data-scroll-target="#two-sample-tests">Two Sample Tests</a></li>
  <li><a href="#matched-pairs-and-repeated-measures" id="toc-matched-pairs-and-repeated-measures" class="nav-link" data-scroll-target="#matched-pairs-and-repeated-measures">Matched Pairs and Repeated Measures</a></li>
  <li><a href="#analysis-of-variance" id="toc-analysis-of-variance" class="nav-link" data-scroll-target="#analysis-of-variance">Analysis of Variance</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistics Primer</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="experimental-design-and-statistical-analysis" class="level1">
<h1>Experimental Design and Statistical Analysis</h1>
<section id="what-is-statistics" class="level2">
<h2 class="anchored" data-anchor-id="what-is-statistics">What is Statistics?</h2>
<p><strong>Statistics</strong> is the science concerned with developing and studying methods for collecting, analyzing, interpreting, and presenting empirical data.</p>
<p>Statistics answers questions like</p>
<ul>
<li>How should I conduct experiments?</li>
<li>What is the best way to test my hypothesis?</li>
<li>What is the true value of ___ and how precisely do I know that value?</li>
<li>What does my experiment/sample value tell me about my data?</li>
<li>What the value of ___ will be in the (near) future</li>
</ul>
<p>Statistics concerns itself with several different (but related) tasks:</p>
<table class="table">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<tbody>
<tr class="odd">
<td><p><strong>Description</strong>: What does the data say?</p>
<p><img src="image/histogram-sample-stats.png" class="img-fluid"></p></td>
<td><p><strong>Inference</strong>: What does the data tell us (about the population)?</p>
<p><img src="image/sample-population.png" class="img-fluid"></p></td>
</tr>
<tr class="even">
<td><p><strong>Experimental Design</strong>: What’s the best way to collect data?</p>
<p><img src="image/wizard-list.png" class="img-fluid"></p></td>
<td><p><strong>Prediction</strong>: What will happen next?</p>
<p><img src="image/crystal-ball-fuzzball.png" class="img-fluid"></p></td>
</tr>
</tbody>
</table>
</section>
<section id="an-historical-example-the-logic-of-statistical-hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="an-historical-example-the-logic-of-statistical-hypothesis-testing">An Historical Example: The Logic of Statistical Hypothesis Testing</h2>
<p>Sir Ronald Fisher once had a conversation with a woman who claimed to be able to tell whether the tea or milk was added first to a cup. Fisher, being interested in probability, decided to test this woman’s claim empirically by presenting her with 8 randomly ordered cups of tea - 4 with milk added first, and 4 with tea added first. The women was then supposed to select 4 cups prepared with one method, but is allowed to directly compare each cup (e.g.&nbsp;tasting each cup sequentially, or in pairs).</p>
<p><img src="image/tea-tasting-fuzzballs.png" class="img-fluid"></p>
<p>The lady identified each cup correctly. Do we believe that this could happen by random chance alone?<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<section id="initial-statistical-setup" class="level3">
<h3 class="anchored" data-anchor-id="initial-statistical-setup">Initial statistical setup</h3>
<ul>
<li><p>Null Hypothesis (what we are hoping to disprove):<br>
There is no observable difference between the two methods of preparing tea (any success is by chance alone).</p></li>
<li><p>Alternative Hypothesis (if random chance isn’t the reason, then what?):<br>
There is an observable difference between the two methods of preparing tea, that is, the woman can actually detect via taste which cups were prepared using either method.</p></li>
</ul>
<p>If the results we observed are due to random chance alone, how common would it be to get 8/8 correct?</p>
</section>
<section id="simulation" class="level3">
<h3 class="anchored" data-anchor-id="simulation">Simulation</h3>
<ol type="1">
<li><p>Flip a coin 4 times to represent the 4 cups identified as containing tea with milk added first. Heads corresponds to a correct decision, Tails to an incorrect decision.</p></li>
<li><p>Record the number of successful selections</p></li>
<li><p>Repeat 100 times to generate a distribution of results under the null hypothesis – that is, what our results would look like if the lady is just guessing.</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2022-Extension-REU_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" style="width:49.5%"></p>
<figcaption class="figure-caption">Simulated results (left), and simulated results evaluated in light of our observed data.</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2022-Extension-REU_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" style="width:49.5%"></p>
<figcaption class="figure-caption">Simulated results (left), and simulated results evaluated in light of our observed data.</figcaption>
</figure>
</div>
</div>
</div>
<p>You can play with different configurations of the tea tasting scenario <a href="https://srvanderplas.shinyapps.io/UNL-APL-workshop/">here</a> or <a href="https://shiny.srvanderplas.com/APL/">here</a> (two links to different servers hosting the same application).</p>
</section>
<section id="strength-of-the-evidence" class="level3">
<h3 class="anchored" data-anchor-id="strength-of-the-evidence">Strength of the Evidence</h3>
<p>Our simulation shows that under random chance, it appears that our tea taster would be expected to identify all of the cups correctly (corresponding to HHHH) 4/100 = 0.04 times.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>0.04 in this example corresponds to our <strong>p-value</strong> - the probability under the null hypothesis of observing the results from our experiment.</p>
</div>
</div>
<p>0.04 is a fairly low value, so we might say that we don’t believe that the results are sufficiently likely under our null hypothesis. In this case, the probability of observing the results under the null hypothesis is low, so we might instead conclude that the alternative hypothesis seems more reasonable – that is, it is more likely that the null hypothesis is wrong. So, we might instead conclude that because our p-value is so low, that is, that we are unlikely to observe results this extreme under random chance, that instead we believe that the lady is not guessing and can actually detect the difference in tea prepared in different ways. We <strong>reject the null hypothesis and conclude that the alternative is more likely</strong>.</p>
<p>Now, in this example, we have a relatively low sample size – which means that it is hard for us to find evidence too much stronger than what our simulation provided for us. In many situations in science, however, we may require <strong>stronger evidence</strong> that the null hypothesis is unlikely to generate results that we have observed – corresponding to requiring a p-value that is lower than 0.05. The correct threshold value (“alpha”) for rejecting a null hypothesis differs by discipline (physics may use values like <span class="math inline">\(10^{-6}\)</span>) and by the consequences of the results (medical trials may require small p-values, while studies looking for avenues to explore may use higher p-values.)</p>
</section>
<section id="connection-to-theory-based-tests" class="level3">
<h3 class="anchored" data-anchor-id="connection-to-theory-based-tests">Connection to Theory-based Tests</h3>
<p>The simulation method described above for evaluating the probability of observing the evidence under the null hypothesis relies on significant manual simulation or outsourcing that work to a computer. The results are not guaranteed to be the same every time, and before computers were common, the manual simulation approach was often too tedious to use regularly. Thus, probability distributions describing the results mathematically were used instead.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/SimulationTheoryCartoon.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Simulated distributions approximate the theoretical distribution, but connect more clearly to real-world ideas.</figcaption>
</figure>
</div>
<p>No matter what distribution the researcher uses to compare to, the basic idea of theory-based statistics is the same: we look for <strong>evidence that our result is (or is not) likely under the null hypothesis</strong>. If the result is likely under the null, then we can’t say anything – we can’t disprove the idea that the results are due to chance. If the result isn’t likely under the null, then we reject the null hypothesis and say the alternative is more likely.</p>
<p>In theory-based tests, this evidence is usually in the form of <strong>a __-value</strong>, where the blank is the name of the distribution (commonly, <span class="math inline">\(z\)</span>, <span class="math inline">\(t\)</span>, <span class="math inline">\(F\)</span>, <span class="math inline">\(\chi^2\)</span>).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/Stat_test_logic.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">The same process used in simulated distributions works in theory-based distributions.</figcaption>
</figure>
</div>
<p>You can play with different simulations and distributions <a href="https://srvanderplas.shinyapps.io/UNL-APL-workshop/">here</a> or <a href="https://shiny.srvanderplas.com/APL/">here</a> (two links to different servers hosting the same application). Use the Distributions tab.</p>
</section>
<section id="understanding-p-values" class="level3">
<h3 class="anchored" data-anchor-id="understanding-p-values">Understanding p-values</h3>
<p>The p-value is the probability of observing the data we saw under the null hypothesis <span class="math inline">\(H_0\)</span>. A p-value is the <strong>area under the reference distribution</strong> where values are <strong>as or more extreme</strong> than the hypothesized value.</p>
<p><img src="image/p-value-logic.png" class="img-fluid"></p>
<p>If the p-value is low (<span class="math inline">\(p &lt; \alpha\)</span>, where <span class="math inline">\(\alpha = 0.05, 0.01\)</span>, or another pre-specified value) then we know that it is relatively unlikely to observe our data under <span class="math inline">\(H_0\)</span>… which means that it is more likely that <span class="math inline">\(H_0\)</span> is false and <span class="math inline">\(H_A\)</span> is true.</p>
<p>When p-values are low, we <strong>reject</strong> <span class="math inline">\(H_0\)</span> and conclude that <span class="math inline">\(H_A\)</span> is more likely.</p>
<p><img src="image/two-sided-test.png" class="img-fluid"></p>
<p>Not all alternative hypotheses are one sided, e.g.&nbsp;<span class="math inline">\(x &gt; a\)</span>. Some hypotheses are two sided - <span class="math inline">\(H_0: x = a\)</span> and <span class="math inline">\(H_A: x \neq a\)</span>. When we have a two-sided hypothesis, we have two areas of our distribution that contribute to the p-value.</p>
</section>
</section>
<section id="estimating-values-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="estimating-values-confidence-intervals">Estimating Values: Confidence Intervals</h2>
<p>Sometimes, we don’t want to test whether a parameter is equal to a specific value - instead, we might want to know what that value is (or at least, a range of possible values for that parameter).</p>
<p>In this case, we construct a <strong>confidence interval</strong> - a set of plausible values for the parameter.</p>
<p>We can think of a confidence interval as our best estimate of the parameter value + uncertainty.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/confidence-interval-best-est-uncertainty.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Confidence intervals are a range of values around the central estimate obtained from the sample data</figcaption>
</figure>
</div>
<p>Confidence intervals, like hypothesis tests, are conducted based on a parameter <span class="math inline">\(\alpha\)</span> representing the acceptable level of error. If we want to be 95% confident in our estimate, our interval will be <strong>wider</strong> than if we want to be 90% confident in our estimate – we have to include more values to get a wider interval.</p>
</section>
<section id="experimental-design" class="level2">
<h2 class="anchored" data-anchor-id="experimental-design">Experimental Design</h2>
<p>Many studies have a design which is more complicated than the simple examples shown in the previous section. However, all of these designs use the same statistical principles - they may just be applied in different ways.</p>
<p>What follows is a brief description and depiction of how these different experimental designs work in practice. Focus primarily on the way the experiments are set up – in the end, there is always a test statistic computed from the sample mean(s) and variance(s) which is compared to a distribution, as described above.</p>
<section id="one-sample-tests" class="level3">
<h3 class="anchored" data-anchor-id="one-sample-tests">One Sample Tests</h3>
<section id="categorical-variables" class="level4">
<h4 class="anchored" data-anchor-id="categorical-variables">Categorical Variables</h4>
<p>In one-sample tests of categorical variables, we typically want to know whether the proportion of successes (the quantity we’re interested in) is equal to a specific value (that is, <span class="math inline">\(\pi = 0.5\)</span> or something of that sort). Our population parameter, <span class="math inline">\(\pi\)</span>, represents the unknown population quantity, and our sample statistic, <span class="math inline">\(\hat p\)</span>, represents what we know about the value of <span class="math inline">\(\pi\)</span>.</p>
<p>In these tests, our <strong>null hypothesis</strong> is that <span class="math inline">\(\pi = a\)</span>, where a is chosen relative to the problem. Often, <span class="math inline">\(a\)</span> is equal to 0.5, because usually that corresponds to random chance.</p>
<p>When simulating these experiments, we will often use a coin flip (for random chance) or a spinner (for other values of <span class="math inline">\(\pi\)</span>) to generate data.</p>
<p>You can play with different one sample categorical tests <a href="https://srvanderplas.shinyapps.io/UNL-APL-workshop/">here</a> or <a href="https://shiny.srvanderplas.com/APL/">here</a> (two links to different servers hosting the same application). Use the One Categorical Variable tab.</p>
</section>
<section id="continuous-variables" class="level4">
<h4 class="anchored" data-anchor-id="continuous-variables">Continuous Variables</h4>
<p>One-sample continuous variable experiments cannot be simulated because we do not usually know the characteristics of the population we’re trying to predict from. Instead, we use theory-based tests for continuous one-sample data.</p>
<p>You can play with different one sample continuous tests <a href="https://srvanderplas.shinyapps.io/UNL-APL-workshop/">here</a> or <a href="https://shiny.srvanderplas.com/APL/">here</a> (two links to different servers hosting the same application). Use the One Continuous Variable tab.</p>
<!-- Two sample test example -->
</section>
</section>
<section id="two-sample-tests" class="level3">
<h3 class="anchored" data-anchor-id="two-sample-tests">Two Sample Tests</h3>
<p>In a two-sample test, there are two groups of participants which are assigned different treatments. The goal is to see how the two treatments differ. Because there are two groups, the mathematical formula for calculating the standardized statistic is slightly more complicated (because the variability of <span class="math inline">\(\overline{X}_A - \overline{X}_B\)</span> is a bit more complicated), but in the end that statistic is compared to a similar reference distribution.</p>
<p><img src="image/unpaired-test.png" class="img-fluid" alt="A two-sample test randomly divides up a sample into two groups and calculates the sample mean for each group."> <!-- Paired vs unpaired tests --></p>
<p>You can play with different two sample categorical tests <a href="https://srvanderplas.shinyapps.io/UNL-APL-workshop/">here</a> or <a href="https://shiny.srvanderplas.com/APL/">here</a> (two links to different servers hosting the same application). Use the Categorical + Continuous Variable tab.</p>
</section>
<section id="matched-pairs-and-repeated-measures" class="level3">
<h3 class="anchored" data-anchor-id="matched-pairs-and-repeated-measures">Matched Pairs and Repeated Measures</h3>
<p>In a variation on this theme, in some cases, we may want to compare two treatments, but we may design the experiment to reduce variability using either repeated measures or matched pairs.</p>
<p>A repeated measures study requires each participant to experience both treatments in the experiment.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/repeated-measures.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">In a repeated measures study, the same individuals see both treatment A and treatment B; this way, each individual serves as their own control</figcaption>
</figure>
</div>
<p>Sometimes, it is not ethical or feasible to give the same individual both treatments – for instance, we cannot ethically or logistically assign mothers to breastfeed or formula feed with the same baby – and so instead, we must create pairs of individuals who are similar.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/matched-pairs.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">In a matched pairs study, we use covariates to match individuals and then assign each individual in a pair to a single treatment. Matched pairs studies reduce variability, but not as much as repeated measures studies</figcaption>
</figure>
</div>
<p>You can play with different matched-pairs and repeated-measures studies <a href="https://srvanderplas.shinyapps.io/UNL-APL-workshop/">here</a> or <a href="https://shiny.srvanderplas.com/APL/">here</a> (two links to different servers hosting the same application). Use the One Continuous Variable tab, and the difference between your matched pairs or repeated measures as your observation.</p>
</section>
<section id="analysis-of-variance" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-variance">Analysis of Variance</h3>
<!-- Multiple variables (ANOVA) -->
<p>In other cases, we may be more interested in sources of variability in the data.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/anova-class.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Suppose we have a group of elementary school children, separated by grade. We want to know if grade is a good predictor of the children’s height.</figcaption>
</figure>
</div>
<p>If a variable is important, then it should account for more variability in the data than the overall variability between two observations. In this example, that means that children within a grade should be more similar than children who are from different grades.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/anova-class-means.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">To get this information, for each group we calculate the group mean</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/anova-class-deviations.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Then, for each individual, we calculate the deviation from the group mean</figcaption>
</figure>
</div>
<p>ANOVA models are sometimes shown in tables like this:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Factor</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">grade</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">56.000000</td>
<td style="text-align: right;">26.25</td>
<td style="text-align: right;">1.26e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">2.133333</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">144</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The overall statistic we calculate is the ratio of the sum-of-squares within groups to the sum-of-squares between groups. The mathematical details of this aren’t that important here, unless they make the process easier to understand.</p>
<p>Between group SS: <span class="math inline">\(6 * (43.77 - 41)^2 + 6* (43 - 43.77)^2 + 6 * (47 - 43.77)^2 = 42.77 + 2.69 + 66.53 = 112\)</span></p>
<p>Within group SS: <span class="math display">\[\left(0^2 + 3^2 + (-1)^2 + 0^2 + (-1)^2 + (-1)^2\right) + \\
\left((-1)^2 + (-1)^2 + 2^2 + (-2)^2 + 1^2 + 1^2\right) + \\
\left(0^2 + 0^2 + 0^2 + 0^2 + (-2)^2 + 2^2\right) = 32\]</span></p>
<p>So by adding the group variable, we reduce our total error from 144 (112 + 32) to 32. Not bad! Put another way, our group variable explains some 77% of the overall variability in the data.</p>
<p>ANOVA models calculate out an F-statistic which is compared to an F-distribution. This F-statistic is calculated as the ratio of the Mean Sq. for each group - the sum of squared errors for each group (between, within) divided by the degrees of freedom (the number of observations - 1). In this case, our F value (with 2, 15 degrees of freedom) is 26.25. This corresponds to a p-value of 0.00001262 – so the chances of observing something this significant when there is in fact no difference between groups is <em>very</em> low.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2022-Extension-REU_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">It is clear that 26.25 is very much in the tails of the F(2, 15) distribution, which explains the extremely low p-value.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear Regression</h3>
<!-- Regression Intro -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/linear-trend.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Two continuous variables may have a linear relationship</figcaption>
</figure>
</div>
<p>It’s fairly common in science to have two continuous quantitative variables – for instance, height and weight, or fertilizer applied and yield. When we have data like this, we use linear regression to fit a regression line to the data. This line minimizes the errors in <span class="math inline">\(y\)</span>, and is sometimes called the <strong>least squares regression line</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/linear-regression-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">We estimate the linear relationship using the least-squares regression line <span class="math inline">\(\hat{y} = a \cdot x + b\)</span>, where <span class="math inline">\(a\)</span> is the slope of the line and <span class="math inline">\(b\)</span> is the y-intercept. <span class="math inline">\(\hat y\)</span> is the predicted value of y at a given value of <span class="math inline">\(x\)</span></figcaption>
</figure>
</div>
<p>Generally, though, our data are not fixed: they are the result of sampling. If this is the case, then we know that a different sample may provide a different result. Thus, we know that any estimates <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> have variability that directly results from <strong>how we collected the data</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/linear-regression-diff-lines.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">If we have a different sample, we may get a different regression line – which means <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> have variability (and a corresponding distribution)</figcaption>
</figure>
</div>
<p>As a result, we generally have a <strong>distribution</strong> of values corresponding to <span class="math inline">\(a\)</span> and a similar <strong>distribution</strong> of values corresponding to <span class="math inline">\(b\)</span>. Because our data are the result of a random sample, we can analyze the least squares regression coefficients using statistical techniques.</p>
<p>We may want to test hypotheses about <span class="math inline">\(a\)</span> such as “Is there a relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>?” (This doesn’t mention <span class="math inline">\(a\)</span>, but if there is no relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, then <span class="math inline">\(a\)</span> would be 0, so implicitly, we’re asking whether <span class="math inline">\(a = 0\)</span>.) Typically, scientists aren’t as interested in the value of <span class="math inline">\(b\)</span>.</p>
<p>We can test these hypotheses using simulation by arranging our data as if there is no relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> - that is, by shuffling our <span class="math inline">\(y\)</span> data to correspond to a random <span class="math inline">\(x\)</span> value in the dataset. Then, we would fit a new regression line and record the value of <span class="math inline">\(a^\ast\)</span> (the simulated <span class="math inline">\(a\)</span>).</p>
<p>Just like before, when we shuffled data or labels, we generate a distribution of <span class="math inline">\(a^\ast\)</span> under the null hypothesis and compare our observed value to that distribution, counting up the number of values which are more extreme.</p>


</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>A more thorough explanation of this experiment is available <a href="https://en.wikipedia.org/wiki/Lady_tasting_tea">here</a> - the tea tasting experiment is one of the pillars of early statistics and randomization-based hypothesis testing.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>